version: '3'

networks:
  default:
    driver: bridge

volumes:
  db-storage:
    driver: local

services:
  web:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - php
      - db

  php:
    container_name: php-app
    build:
      dockerfile: ./php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/conf.d/opcache-dev.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./app:/var/www/html
    depends_on:
      composer:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  composer:
    image: composer
    volumes:
      - ./app:/app
    command: install

  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    env_file:
      - ./postgres/.env
    ports:
      - 5432:5432
    volumes:
      - db-storage:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 5s
      retries: 5

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
