version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - php
      - db

  php:
    build:
      dockerfile: ./php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./app:/var/www/html

  composer:
    image: composer
    volumes:
      - ./app:/app
    command: install

  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./postgres/.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
