version: '3'

networks:
  default:
    driver: bridge

services:
  web:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - php
      - db

  php:
    build:
      dockerfile: ./php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./app:/var/www/html

  composer:
    image: composer
    volumes:
      - ./app:/app
    command: install
