version: '3'

networks:
  default:
    driver: bridge

services:
  web:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - php

  php:
    container_name: php-app
    build:
      dockerfile: ./php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php/www.conf:/usr/local/etc/php/php-fpm.d/www.conf
      - ./app:/var/www/html
    depends_on:
      composer:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 5s
      retries: 5

  composer:
    image: composer
    volumes:
      - ./app:/app
    command: install
